/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ims;

/**
 *
 * @author LENOVO
 */
public class ADashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public ADashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MProduct = new javax.swing.JMenu();
        MSupplier = new javax.swing.JMenu();
        MWarehouse = new javax.swing.JMenu();
        s_t_w = new javax.swing.JMenuItem();
        Showroom = new javax.swing.JMenu();
        w_t_s = new javax.swing.JMenuItem();
        close = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MProduct.setText("Product");
        MProduct.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                MProductMenuSelected(evt);
            }
        });
        
        
        jMenuBar1.add(MProduct);

        MSupplier.setText("Supplier");
        jMenuBar1.add(MSupplier);

        MWarehouse.setText("Warehouse");

        s_t_w.setText("Supplier to Warehouse");
        
        MWarehouse.add(s_t_w);

        jMenuBar1.add(MWarehouse);

        Showroom.setText("Showroom");

        w_t_s.setText("Warehouse to Showroom");
        Showroom.add(w_t_s);

        jMenuBar1.add(Showroom);

        close.setText("Close");
        jMenuBar1.add(close);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MProductMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MProductMenuSelected
        dispose();
        new Product().setVisible(true);
    }//GEN-LAST:event_MProductMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MProduct;
    private javax.swing.JMenu MSupplier;
    private javax.swing.JMenu MWarehouse;
    private javax.swing.JMenu Showroom;
    private javax.swing.JMenu close;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem s_t_w;
    private javax.swing.JMenuItem w_t_s;
    // End of variables declaration//GEN-END:variables
}
